### ISSUE TITLE
Activate the lsp client for files without extension

### ISSUE THREAD

**Issue by BNMetrics** [gtache/intellij-lsp#40]
First of all, thanks so much for making this plugin! :)

I have noticed this lsp client plugin activates when the files matches certain extention is opened in the IDE, I'm just wondering if there is a way to configure the plugin so it would be able to recognise files without extension, for example `Dockerfile`?

I'm currently writing my own language server, and the files don't usually have an extension.

Thanks again! :)

**Comment by gtache** [comment]
Okay, this is implemented in 1.5.0

You can right click in the editor, on an editor tab or the project view (can also select multiple files there), "Link to LSP server..." and then select the server definition extension you want to attach the file(s) to (in your case, if your server doesn't look at extension, you can just put a name for your server instead of an extension in the definition). It will also be saved, so next time you open the IDE it will remember the associations.

You can reset the associations in the Settings -> Language Server Protocol -> Reset associations (or by removing the server definition)

**Comment by nixel2007** [comment]
@gtache when do you plan to release 1.5.0? :)

**Comment by gtache** [comment]
@nixel2007 This week probably, I'm waiting on @NipunaRanasinghe PR and then it should be good to go.

**Comment by NipunaRanasinghe** [comment]
@gtache Oh I somehow missed your last review :( please check and verify the fix.
